name: iOSLocalAIAssistant
options:
  bundleIdPrefix: com.localaiassistant
  deploymentTarget:
    iOS: "17.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

packages: {}

targets:
  iOSLocalAIAssistant:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: App
      - path: Models
      - path: Views
      - path: ViewModels
      - path: Services
      - path: Utilities
      - path: ContentView.swift
      - path: iOSLocalAIAssistantApp.swift
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.localaiassistant.app
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "17.0"
      TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: iOSLocalAIAssistant/Info.plist
      properties:
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: true
